import type { Metadata, Viewport } from 'next';

/* ================== ONE PLACE TO CHANGE BRAND SETTINGS ================== */

export const BRAND = 'AuroWater'; // change to 'AuroTap' here and it updates everywhere
export const APP_ORIGIN = (process.env.NEXT_PUBLIC_SITE_URL ?? 'https://aurotap.in').replace(/\/$/, '');
export const SITE_URL = APP_ORIGIN; // alias used by sitemap.ts and robots.ts
export const TWITTER_HANDLE = '@AuroWater';

/**
 * Share image.
 * '/opengraph-image' is generated by src/app/opengraph-image.tsx (always exists).
 * If you have a designed file at public/og-image.png, set this to '/og-image.png'
 * and delete src/app/opengraph-image.tsx.
 */
export const OG_IMAGE = '/opengraph-image';

export const SITE = {
  name: BRAND,
  tagline: 'Fresh Water Delivery in Gorakhpur, Kanpur & Lucknow',
  description:
    'Book fresh drinking water delivery at your door in Gorakhpur, Kanpur and Lucknow. Easy booking, trusted suppliers, order tracking and loyalty rewards.',
  email: 'team@neurolinkxtech.com',
  cities: ['Gorakhpur', 'Kanpur', 'Lucknow'],
  logo: `${APP_ORIGIN}/icons/icon-512x512.png`,
  // Add real social profile URLs here (leave empty if none yet)
  sameAs: [] as string[],
};

/* ================== YOUR EXISTING EXPORTS (kept, same names) ================== */

export const BASE_META = {

  metadataBase: new URL(APP_ORIGIN),
  openGraph: { siteName: BRAND, locale: 'en_IN', type: 'website' as const },
  twitter: { card: 'summary_large_image' as const, site: TWITTER_HANDLE },
};

/**
 * Use in any public page:
 *   export const metadata = pageMeta('Book Water Delivery', 'Order fresh water in minutes.', '/book');
 */
export function pageMeta(title: string, description: string, path = '/'): Metadata {
  const url = `${APP_ORIGIN}${path === '/' ? '' : path}`;
  return {
    ...BASE_META,
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      ...BASE_META.openGraph,
      title,
      description,
      url,
      images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: title }],
    },
    twitter: {
      ...BASE_META.twitter,
      title,
      description,
      images: [OG_IMAGE],
    },
  };
}


/* ================== SITE-WIDE METADATA (used in layout.tsx) ================== */

export const siteMetadata: Metadata = {
  metadataBase: new URL(APP_ORIGIN),
  title: {
    default: `${BRAND} – ${SITE.tagline}`,
    template: `%s | ${BRAND}`,
  },
  description: SITE.description,
  applicationName: BRAND,
  keywords: [
    'water delivery Gorakhpur',
    'water delivery Kanpur',
    'water delivery Lucknow',
    'drinking water home delivery',
    'water tanker booking UP',
    'RO water delivery',
    BRAND,
  ],
  authors: [{ name: BRAND, url: APP_ORIGIN }],
  creator: BRAND,
  publisher: BRAND,
  category: 'utilities',
  formatDetection: { email: false, address: false, telephone: false },
  manifest: '/manifest.webmanifest',
  openGraph: {
    ...BASE_META.openGraph,
    url: APP_ORIGIN,
    title: `${BRAND} – ${SITE.tagline}`,
    description: SITE.description,
    images: [{ url: OG_IMAGE, width: 1200, height: 630, alt: `${BRAND} – ${SITE.tagline}` }],
  },

  twitter: {
    ...BASE_META.twitter,
    title: `${BRAND} – ${SITE.tagline}`,
    description: SITE.description,
    images: [OG_IMAGE],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  appleWebApp: { capable: true, title: BRAND, statusBarStyle: 'black-translucent' },
  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
  },
};

export const siteViewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  themeColor: '#06B6D4',
  colorScheme: 'dark light',
};

/* ================== JSON-LD (structured data for Google) ================== */


export const siteJsonLd = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'Organization',
      '@id': `${APP_ORIGIN}/#organization`,
      name: BRAND,
      url: APP_ORIGIN,
      logo: SITE.logo,
      email: SITE.email,
      ...(SITE.sameAs.length ? { sameAs: SITE.sameAs } : {}),
    },
    {
      '@type': 'WebSite',
      '@id': `${APP_ORIGIN}/#website`,
      url: APP_ORIGIN,
      name: BRAND,
      description: SITE.description,
      inLanguage: 'en-IN',
      publisher: { '@id': `${APP_ORIGIN}/#organization` },
    },
    {
      '@type': 'LocalBusiness',
      '@id': `${APP_ORIGIN}/#localbusiness`,
      name: BRAND,
      url: APP_ORIGIN,
      image: SITE.logo,
      description: SITE.description,
      email: SITE.email,
      priceRange: '₹',
      areaServed: SITE.cities.map((city) => ({
        '@type': 'City',

        name: city,
        containedInPlace: { '@type': 'AdministrativeArea', name: 'Uttar Pradesh' },
      })),
      parentOrganization: { '@id': `${APP_ORIGIN}/#organization` },
      makesOffer: {
        '@type': 'Offer',
        itemOffered: {
          '@type': 'Service',
          name: 'Drinking water home delivery',
          serviceType: 'Water delivery',
          areaServed: SITE.cities,
        },
      },
    },
  ],
};






// import type { Metadata } from 'next';

// export const APP_ORIGIN = 'https://aurotap.in';

// export const BASE_META = {
//   metadataBase: new URL(APP_ORIGIN),
//   openGraph: { siteName: 'AuroWater', locale: 'en_IN', type: 'website' as const },
//   twitter: { card: 'summary_large_image' as const, site: '@AuroWater' },
// };

// export function pageMeta(title: string, description: string, path = '/'): Metadata {
//   const url = `${APP_ORIGIN}${path}`;
//   return {
//     ...BASE_META,
//     title,
//     description,
//     alternates: { canonical: url },
//     openGraph: {
//       ...BASE_META.openGraph,
//       title,
//       description,
//       url,
//       images: [{ url: '/og-image.png', width: 1200, height: 630, alt: title }],
//     },
//     twitter: {
//       ...BASE_META.twitter,
//       title,
//       description,
//       images: ['/og-image.png'],
//     },
//   };
// }
