-- AUTO-GENERATED by scripts/build-supabase-migrations.mjs — do not edit by hand.
-- Run in Supabase SQL Editor (Project → SQL) in order is already preserved.


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/001_core_schema.sql
-- ═══════════════════════════════════════════════════════════════

-- AuroWater — core schema (Supabase / PostgreSQL)
-- Idempotent: safe to run multiple times.
-- Requires: auth.users (Supabase Auth)

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ── Users (extends Supabase auth.users) ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
  id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name       TEXT NOT NULL DEFAULT '',
  email           TEXT NOT NULL UNIQUE,
  phone           TEXT,
  role            TEXT NOT NULL DEFAULT 'customer'
                    CHECK (role IN ('customer','technician','supplier','admin')),
  aurotap_id      TEXT UNIQUE,
  avatar_url      TEXT,
  is_active       BOOLEAN NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Service types ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.service_types (
  id          SERIAL PRIMARY KEY,
  key         TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  description TEXT,
  base_price  NUMERIC(10,2) NOT NULL DEFAULT 0,
  unit        TEXT NOT NULL DEFAULT 'per visit',
  is_active   BOOLEAN NOT NULL DEFAULT true,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

-- ── Addresses ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.addresses (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  label       TEXT DEFAULT 'Home',
  house_flat  TEXT NOT NULL,
  area        TEXT NOT NULL,
  city        TEXT NOT NULL,
  pincode     TEXT NOT NULL,
  landmark    TEXT,
  is_default  BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Orders ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.orders (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number        TEXT UNIQUE NOT NULL,
  customer_id         UUID NOT NULL REFERENCES public.profiles(id),
  supplier_id         UUID REFERENCES public.profiles(id),
  technician_id       UUID REFERENCES public.profiles(id),
  service_type_id     INTEGER NOT NULL REFERENCES public.service_types(id),
  sub_option_key      TEXT,
  address_id          UUID REFERENCES public.addresses(id),
  address_snapshot    JSONB,
  scheduled_date      DATE,
  time_slot           TEXT,
  scheduled_time      TIMESTAMPTZ,
  status              TEXT NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING','ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED')),
  base_amount         NUMERIC(10,2) NOT NULL DEFAULT 0,
  convenience_fee     NUMERIC(10,2) NOT NULL DEFAULT 29,
  emergency_charge    NUMERIC(10,2) NOT NULL DEFAULT 0,
  gst_amount          NUMERIC(10,2) NOT NULL DEFAULT 0,
  total_amount        NUMERIC(10,2) NOT NULL DEFAULT 0,
  supplier_payout     NUMERIC(10,2) NOT NULL DEFAULT 0,
  platform_fee        NUMERIC(10,2) NOT NULL DEFAULT 0,
  payment_method      TEXT DEFAULT 'cash' CHECK (payment_method IN ('cash','online','upi','card')),
  payment_status      TEXT NOT NULL DEFAULT 'unpaid'
                        CHECK (payment_status IN ('unpaid','paid','refunded')),
  payout_status       TEXT NOT NULL DEFAULT 'pending'
                        CHECK (payout_status IN ('pending','processing','paid')),
  is_emergency        BOOLEAN NOT NULL DEFAULT false,
  cancellation_reason TEXT,
  notes               TEXT,
  can_quantity        INTEGER,
  can_price_per_unit  NUMERIC(10,2),
  can_order_type      TEXT CHECK (can_order_type IS NULL OR can_order_type IN ('one_time','subscription')),
  can_frequency       TEXT CHECK (can_frequency IS NULL OR can_frequency IN ('daily','alternate','weekly')),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Settings (key-value) ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.settings (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Payouts ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.payouts (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  supplier_id UUID NOT NULL REFERENCES public.profiles(id),
  amount      NUMERIC(10,2) NOT NULL,
  method      TEXT,
  reference   TEXT,
  paid_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  notes       TEXT
);

-- ── Reviews ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.reviews (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id    UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  customer_id UUID NOT NULL REFERENCES public.profiles(id),
  rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT reviews_order_unique UNIQUE (order_id)
);

-- ── Notifications ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.notifications (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  body        TEXT NOT NULL,
  type        TEXT NOT NULL DEFAULT 'system',
  order_id    UUID REFERENCES public.orders(id),
  is_read     BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Contact submissions (marketing / support) ───────────────────────
CREATE TABLE IF NOT EXISTS public.contact_submissions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL,
  email       TEXT NOT NULL,
  phone       TEXT,
  message     TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Founding members counter (social proof) ──────────────────────────
CREATE TABLE IF NOT EXISTS public.founding_members (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT,
  email       TEXT,
  phone       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS founding_members_phone_key ON public.founding_members (phone)
  WHERE phone IS NOT NULL AND phone <> '';


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/002_rls_policies.sql
-- ═══════════════════════════════════════════════════════════════

-- RLS policies for AuroWater (Supabase)
-- Idempotent: DROP POLICY IF EXISTS + CREATE POLICY

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.founding_members ENABLE ROW LEVEL SECURITY;

-- ── Helper: current profile role (avoids recursion in simple cases) ──
CREATE OR REPLACE FUNCTION public.current_profile_role()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid() LIMIT 1;
$$;

-- ── profiles ───────────────────────────────────────────────────────
DROP POLICY IF EXISTS "profiles_select_own_or_admin" ON public.profiles;
CREATE POLICY "profiles_select_own_or_admin" ON public.profiles
  FOR SELECT USING (
    auth.uid() = id OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "profiles_update_own_or_admin" ON public.profiles;
CREATE POLICY "profiles_update_own_or_admin" ON public.profiles
  FOR UPDATE USING (
    auth.uid() = id OR COALESCE(public.current_profile_role(), '') = 'admin'
  )
  WITH CHECK (
    auth.uid() = id OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

-- Inserts handled by trigger / service role on signup
DROP POLICY IF EXISTS "profiles_insert_admin" ON public.profiles;
CREATE POLICY "profiles_insert_admin" ON public.profiles
  FOR INSERT WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── service_types (public read active; admin write) ─────────────────
DROP POLICY IF EXISTS "service_types_select_all" ON public.service_types;
CREATE POLICY "service_types_select_all" ON public.service_types
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "service_types_write_admin" ON public.service_types;
CREATE POLICY "service_types_write_admin" ON public.service_types
  FOR ALL USING (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── addresses ───────────────────────────────────────────────────────
DROP POLICY IF EXISTS "addresses_crud_own" ON public.addresses;
CREATE POLICY "addresses_crud_own" ON public.addresses
  FOR ALL USING (
    user_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  )
  WITH CHECK (
    user_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

-- ── orders ──────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "orders_select_policy" ON public.orders;
CREATE POLICY "orders_select_policy" ON public.orders
  FOR SELECT USING (
    customer_id = auth.uid()
    OR supplier_id = auth.uid()
    OR technician_id = auth.uid()
    OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "orders_insert_customer" ON public.orders;
CREATE POLICY "orders_insert_customer" ON public.orders
  FOR INSERT WITH CHECK (customer_id = auth.uid());

DROP POLICY IF EXISTS "orders_update_roles" ON public.orders;
CREATE POLICY "orders_update_roles" ON public.orders
  FOR UPDATE USING (
    customer_id = auth.uid()
    OR supplier_id = auth.uid()
    OR technician_id = auth.uid()
    OR COALESCE(public.current_profile_role(), '') = 'admin'
  )
  WITH CHECK (
    customer_id = auth.uid()
    OR supplier_id = auth.uid()
    OR technician_id = auth.uid()
    OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "orders_delete_admin" ON public.orders;
CREATE POLICY "orders_delete_admin" ON public.orders
  FOR DELETE USING (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── settings ───────────────────────────────────────────────────────
DROP POLICY IF EXISTS "settings_select_all" ON public.settings;
CREATE POLICY "settings_select_all" ON public.settings
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "settings_write_admin" ON public.settings;
CREATE POLICY "settings_write_admin" ON public.settings
  FOR INSERT WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

DROP POLICY IF EXISTS "settings_update_admin" ON public.settings;
CREATE POLICY "settings_update_admin" ON public.settings
  FOR UPDATE USING (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── payouts ─────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "payouts_select" ON public.payouts;
CREATE POLICY "payouts_select" ON public.payouts
  FOR SELECT USING (
    supplier_id = auth.uid()
    OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "payouts_write_admin" ON public.payouts;
CREATE POLICY "payouts_write_admin" ON public.payouts
  FOR INSERT WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── reviews ───────────────────────────────────────────────────────
DROP POLICY IF EXISTS "reviews_select_all" ON public.reviews;
CREATE POLICY "reviews_select_all" ON public.reviews
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "reviews_insert_customer" ON public.reviews;
CREATE POLICY "reviews_insert_customer" ON public.reviews
  FOR INSERT WITH CHECK (customer_id = auth.uid());

-- ── notifications ───────────────────────────────────────────────────
DROP POLICY IF EXISTS "notifications_select_own" ON public.notifications;
CREATE POLICY "notifications_select_own" ON public.notifications
  FOR SELECT USING (
    user_id = auth.uid()
    OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "notifications_update_own" ON public.notifications;
CREATE POLICY "notifications_update_own" ON public.notifications
  FOR UPDATE USING (user_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin');

DROP POLICY IF EXISTS "notifications_insert_admin" ON public.notifications;
CREATE POLICY "notifications_insert_admin" ON public.notifications
  FOR INSERT WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── contact_submissions (public insert for contact form; admin read) ─
DROP POLICY IF EXISTS "contact_select_admin" ON public.contact_submissions;
DROP POLICY IF EXISTS "contact_insert_any" ON public.contact_submissions;
CREATE POLICY "contact_select_admin" ON public.contact_submissions
  FOR SELECT USING (COALESCE(public.current_profile_role(), '') = 'admin');
CREATE POLICY "contact_insert_any" ON public.contact_submissions
  FOR INSERT WITH CHECK (true);

-- ── founding_members ────────────────────────────────────────────────
DROP POLICY IF EXISTS "founding_select_all" ON public.founding_members;
CREATE POLICY "founding_select_all" ON public.founding_members
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "founding_insert_own" ON public.founding_members;
CREATE POLICY "founding_insert_own" ON public.founding_members
  FOR INSERT WITH CHECK (true);


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/003_seed_settings.sql
-- ═══════════════════════════════════════════════════════════════

-- Default platform settings + service catalogue
-- Idempotent

INSERT INTO public.service_types (key, name, description, base_price, unit, is_active, sort_order) VALUES
  ('water_can', 'Water Can (20L)', 'RO-purified BIS-certified 20L sealed water cans.', 12, 'per can', true, 1),
  ('water_tanker', 'Water Tanker', 'Bulk water delivery via tanker.', 299, 'per delivery', true, 2),
  ('ro_service', 'RO Service & Repair', 'RO purifier service, filter change, AMC.', 199, 'per visit', true, 3),
  ('plumbing', 'Plumbing', 'Pipe fitting, leakage repair, installation.', 149, 'per visit', true, 4),
  ('borewell', 'Borewell Services', 'Borewell drilling, repair, motor fitting.', 499, 'per service', true, 5),
  ('motor_pump', 'Motor & Pump Repair', 'Submersible motor repair, pump installation.', 249, 'per visit', true, 6),
  ('tank_cleaning', 'Water Tank Cleaning', 'Overhead/underground tank cleaning.', 349, 'per tank', true, 7)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.settings (key, value) VALUES
  ('default_can_price',        '12'),
  ('subscription_can_price',   '10'),
  ('bulk_can_price',           '9'),
  ('bulk_threshold',           '50'),
  ('market_can_price',         '20'),
  ('water_tanker_price',       '299'),
  ('ro_service_price',         '199'),
  ('plumbing_price',           '149'),
  ('borewell_price',           '499'),
  ('motor_pump_price',         '249'),
  ('tank_cleaning_price',      '349'),
  ('convenience_fee',          '29'),
  ('emergency_surcharge',      '199'),
  ('gst_rate',                 '18'),
  ('bulk_commission',          '8'),
  ('technician_commission',    '50'),
  ('supplier_commission',      '30'),
  ('support_email',            'support.aurotap@gmail.com'),
  ('secondary_email',          'aurotap@gmail.com'),
  ('phone_primary',            '9889305803'),
  ('phone_secondary',          ''),
  ('office_address',           'Kanpur, Uttar Pradesh'),
  ('working_hours',            '09:00–21:00 IST'),
  ('brand_name',               'Auro Water'),
  ('whatsapp_enabled',         '1'),
  ('service_base_prices',      '{"water_tanker":299,"ro_service":199,"plumbing":149,"borewell":499,"motor_pump":249,"tank_cleaning":349}')
ON CONFLICT (key) DO NOTHING;


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/004_functions.sql
-- ═══════════════════════════════════════════════════════════════

-- Functions, triggers, auth profile bootstrap

-- ── 1) Order number generator ───────────────────────────────────────
CREATE OR REPLACE FUNCTION public.generate_order_number()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  candidate TEXT;
  tries INT := 0;
BEGIN
  LOOP
    candidate := 'AW-' || lpad((floor(random() * 100000000))::text, 8, '0');
    tries := tries + 1;
    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.orders o WHERE o.order_number = candidate);
    EXIT WHEN tries > 50;
  END LOOP;
  IF tries > 50 THEN
    candidate := 'AW-' || replace(gen_random_uuid()::text, '-', '');
    candidate := left(candidate, 11);
  END IF;
  RETURN candidate;
END;
$$;

-- ── 2) updated_at trigger ───────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_updated_at ON public.profiles;
CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

DROP TRIGGER IF EXISTS orders_updated_at ON public.orders;
CREATE TRIGGER orders_updated_at
  BEFORE UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ── 3) New Supabase Auth user → profile row ─────────────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  r TEXT;
  phone_val TEXT;
BEGIN
  r := COALESCE(NEW.raw_user_meta_data->>'role', 'customer');
  IF r NOT IN ('customer','technician','supplier','admin') THEN
    r := 'customer';
  END IF;
  phone_val := NULLIF(TRIM(COALESCE(NEW.raw_user_meta_data->>'phone', '')), '');
  INSERT INTO public.profiles (id, full_name, email, phone, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(NEW.email, ''),
    phone_val,
    r
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(NULLIF(EXCLUDED.full_name, ''), public.profiles.full_name);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS aurowater_on_auth_user_created ON auth.users;
CREATE TRIGGER aurowater_on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── 4) Customer stats ───────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_customer_stats(p_customer_id UUID)
RETURNS TABLE (
  total_orders BIGINT,
  completed_orders BIGINT,
  total_spent NUMERIC,
  estimated_savings NUMERIC
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    COUNT(*)::BIGINT,
    COUNT(*) FILTER (WHERE o.status = 'COMPLETED')::BIGINT,
    COALESCE(SUM(o.total_amount) FILTER (WHERE o.status = 'COMPLETED' AND o.payment_status = 'paid'), 0)::NUMERIC,
    COALESCE(SUM(o.total_amount) FILTER (WHERE o.status = 'COMPLETED') * 0.35, 0)::NUMERIC
  FROM public.orders o
  WHERE o.customer_id = p_customer_id;
$$;

-- ── 5) Supplier earnings by period ────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_supplier_earnings(p_supplier_id UUID, p_period TEXT)
RETURNS TABLE (
  period_label TEXT,
  order_count BIGINT,
  gross_amount NUMERIC,
  pending_payout NUMERIC
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  start_ts TIMESTAMPTZ;
  pl TEXT;
BEGIN
  pl := lower(coalesce(p_period, 'month'));
  start_ts := CASE pl
    WHEN 'today' THEN date_trunc('day', NOW())
    WHEN 'week' THEN date_trunc('week', NOW())
    WHEN 'month' THEN date_trunc('month', NOW())
    ELSE date_trunc('month', NOW())
  END;

  RETURN QUERY
  SELECT
    pl::TEXT,
    COUNT(*)::BIGINT,
    COALESCE(SUM(o.total_amount) FILTER (WHERE o.status = 'COMPLETED'), 0)::NUMERIC,
    COALESCE(SUM(o.supplier_payout) FILTER (WHERE o.payout_status = 'pending'), 0)::NUMERIC
  FROM public.orders o
  WHERE o.supplier_id = p_supplier_id
    AND o.created_at >= start_ts;
END;
$$;

-- Default order numbers when not supplied by app
ALTER TABLE public.orders
  ALTER COLUMN order_number SET DEFAULT (public.generate_order_number());


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/005_notifications_dedup.sql
-- ═══════════════════════════════════════════════════════════════

-- 005_notifications_dedup.sql
ALTER TABLE public.notifications
  ADD COLUMN IF NOT EXISTS dedup_key text;

DROP INDEX IF EXISTS notifications_user_dedup_key_idx;

CREATE UNIQUE INDEX IF NOT EXISTS notifications_dedup_key_idx
  ON public.notifications (dedup_key)
  WHERE dedup_key IS NOT NULL;

-- Enable Realtime (run on Supabase Postgres; skip if tables are already in publication)
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/006_schema_compat.sql
-- ═══════════════════════════════════════════════════════════════

-- 006_schema_compat.sql — additive fixes for code↔schema alignment (idempotent, no data deletion)
-- Run after 001–005. Safe to re-run.

-- Reviews flow: customer API updates orders.has_review
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS has_review BOOLEAN NOT NULL DEFAULT false;

-- Admin dashboard KPI: online technicians count
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS is_online BOOLEAN NOT NULL DEFAULT false;

-- Optional KPI tables referenced by /api/admin/dashboard (minimal stubs)
CREATE TABLE IF NOT EXISTS public.applications (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  type       TEXT NOT NULL DEFAULT 'supplier' CHECK (type IN ('supplier','technician')),
  payload    JSONB NOT NULL DEFAULT '{}'::jsonb,
  status     TEXT NOT NULL DEFAULT 'pending',
  reviewed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  rejection_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.fraud_flags (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  resolved   BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fraud_flags ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "applications_admin_all" ON public.applications;
CREATE POLICY "applications_admin_all" ON public.applications
  FOR ALL USING (COALESCE(public.current_profile_role(), '') = 'admin')
  WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

DROP POLICY IF EXISTS "fraud_flags_admin_all" ON public.fraud_flags;
CREATE POLICY "fraud_flags_admin_all" ON public.fraud_flags
  FOR ALL USING (COALESCE(public.current_profile_role(), '') = 'admin')
  WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- Refresh PostgREST schema cache so /rest/v1/rpc and table routes see DDL above immediately.
-- Fixes persistent PGRST205 ("could not find the table in the schema cache") after migrations.
NOTIFY pgrst, 'reload schema';


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/006_production_readiness.sql
-- ═══════════════════════════════════════════════════════════════

-- sql/006_production_readiness.sql
-- Run AFTER sql/006_schema_compat.sql (or paste after full bundle).
-- Idempotent: no DROP, no RLS replacement (002_rls_policies.sql stays authoritative).

-- ── Ensure profile display IDs for existing rows ─────────────────────────
UPDATE public.profiles
SET aurotap_id = 'AW-' || upper(left(replace(id::text, '-', ''), 8))
WHERE aurotap_id IS NULL OR trim(both from aurotap_id) = '';

-- ── Service catalogue: bump metadata if seeds changed (matches app keys) ─
INSERT INTO public.service_types (key, name, description, base_price, unit, is_active, sort_order)
VALUES
  ('water_can', 'Water Can (20L)', 'RO-purified 20L cans', 12, 'per can', true, 1),
  ('water_tanker', 'Water Tanker', 'Bulk water delivery', 299, 'per delivery', true, 2),
  ('ro_service', 'RO Service & Repair', 'RO purifier service and repair', 199, 'per visit', true, 3),
  ('plumbing', 'Plumbing', 'Pipe fitting and repair', 149, 'per visit', true, 4),
  ('borewell', 'Borewell Services', 'Drilling and repair', 499, 'per service', true, 5),
  ('motor_pump', 'Motor & Pump Repair', 'Pump installation/repair', 249, 'per visit', true, 6),
  ('tank_cleaning', 'Water Tank Cleaning', 'Tank cleaning', 349, 'per tank', true, 7)
ON CONFLICT (key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  base_price = EXCLUDED.base_price,
  unit = EXCLUDED.unit,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

-- ── Reload PostgREST schema cache ───────────────────────────────────────
SELECT pg_notify('pgrst', 'reload schema');

-- ── Verification (expect 8 rows when core migration applied) ─────────────
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
    'profiles', 'orders', 'addresses', 'service_types',
    'settings', 'notifications', 'reviews', 'payouts'
  )
ORDER BY table_name;


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/007_supplier_milestones.sql
-- ═══════════════════════════════════════════════════════════════

-- Supplier milestone system + supplier settings tables used by the app.
-- Idempotent and safe to re-run.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── profiles: milestone fields ────────────────────────────────────
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS completed_orders integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS milestone_tier   text NOT NULL DEFAULT 'starter'
    CHECK (milestone_tier IN ('starter','bronze','silver','gold','platinum')),
  ADD COLUMN IF NOT EXISTS last_seen_at     timestamptz,
  ADD COLUMN IF NOT EXISTS status           text NOT NULL DEFAULT 'active'
    CHECK (status IN ('active','suspended','pending'));

-- ── supplier_settings ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.supplier_settings (
  user_id         uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  is_online       boolean NOT NULL DEFAULT false,
  price_per_can   numeric(10,2) NOT NULL DEFAULT 12,
  service_radius  integer NOT NULL DEFAULT 5,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.supplier_settings
  ADD COLUMN IF NOT EXISTS zone_radius_km  integer NOT NULL DEFAULT 5,
  ADD COLUMN IF NOT EXISTS commission_rate numeric(4,2) NOT NULL DEFAULT 8.00,
  ADD COLUMN IF NOT EXISTS is_primary_zone boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS auto_accept     boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS upi_id          text,
  ADD COLUMN IF NOT EXISTS bank_account    text,
  ADD COLUMN IF NOT EXISTS ifsc            text,
  ADD COLUMN IF NOT EXISTS qr_code_url     text;

-- Keep the legacy `service_radius` aligned with `zone_radius_km` for older codepaths.
CREATE OR REPLACE FUNCTION public.sync_supplier_radius()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.zone_radius_km IS NOT NULL THEN
    NEW.service_radius := NEW.zone_radius_km;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS supplier_settings_sync_radius ON public.supplier_settings;
CREATE TRIGGER supplier_settings_sync_radius
  BEFORE INSERT OR UPDATE ON public.supplier_settings
  FOR EACH ROW EXECUTE FUNCTION public.sync_supplier_radius();

DROP TRIGGER IF EXISTS supplier_settings_updated_at ON public.supplier_settings;
CREATE TRIGGER supplier_settings_updated_at
  BEFORE UPDATE ON public.supplier_settings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

ALTER TABLE public.supplier_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "supplier_settings_select_own_or_admin" ON public.supplier_settings;
CREATE POLICY "supplier_settings_select_own_or_admin" ON public.supplier_settings
  FOR SELECT USING (
    user_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "supplier_settings_update_own_or_admin" ON public.supplier_settings;
CREATE POLICY "supplier_settings_update_own_or_admin" ON public.supplier_settings
  FOR UPDATE USING (
    user_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  )
  WITH CHECK (
    user_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "supplier_settings_insert_admin" ON public.supplier_settings;
CREATE POLICY "supplier_settings_insert_admin" ON public.supplier_settings
  FOR INSERT WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── supplier_stock (used by seed + supplier flows) ─────────────────
CREATE TABLE IF NOT EXISTS public.supplier_stock (
  supplier_id     uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  cans_available  integer NOT NULL DEFAULT 0,
  low_stock_alert integer NOT NULL DEFAULT 10,
  updated_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.supplier_stock ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "supplier_stock_select_own_or_admin" ON public.supplier_stock;
CREATE POLICY "supplier_stock_select_own_or_admin" ON public.supplier_stock
  FOR SELECT USING (
    supplier_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "supplier_stock_update_own_or_admin" ON public.supplier_stock;
CREATE POLICY "supplier_stock_update_own_or_admin" ON public.supplier_stock
  FOR UPDATE USING (
    supplier_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  )
  WITH CHECK (
    supplier_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "supplier_stock_insert_admin" ON public.supplier_stock;
CREATE POLICY "supplier_stock_insert_admin" ON public.supplier_stock
  FOR INSERT WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── supplier_milestones ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.supplier_milestones (
  id           uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  supplier_id  uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  tier         text NOT NULL,
  unlocked_at  timestamptz NOT NULL DEFAULT now(),
  bonus_amount numeric(10,2) DEFAULT 0,
  notified     boolean NOT NULL DEFAULT false
);

-- ── atomic increment helper (used by admin order completion) ───────
CREATE OR REPLACE FUNCTION public.increment_supplier_completed_orders(p_supplier_id uuid)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.profiles
  SET completed_orders = completed_orders + 1
  WHERE id = p_supplier_id;
$$;

ALTER TABLE public.supplier_milestones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "supplier_milestones_select_own_or_admin" ON public.supplier_milestones;
CREATE POLICY "supplier_milestones_select_own_or_admin" ON public.supplier_milestones
  FOR SELECT USING (
    supplier_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "supplier_milestones_insert_admin" ON public.supplier_milestones;
CREATE POLICY "supplier_milestones_insert_admin" ON public.supplier_milestones
  FOR INSERT WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── audit_logs (used by admin/settings + routing fallback audits) ───
CREATE TABLE IF NOT EXISTS public.audit_logs (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_id   uuid REFERENCES public.profiles(id),
  action     text NOT NULL,
  entity     text NOT NULL,
  entity_id  text NOT NULL,
  meta       jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "audit_logs_admin_all" ON public.audit_logs;
CREATE POLICY "audit_logs_admin_all" ON public.audit_logs
  FOR ALL USING (COALESCE(public.current_profile_role(), '') = 'admin')
  WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── settings: founding member discount key ──────────────────────────
INSERT INTO public.settings (key, value)
VALUES ('founding_member_discount', '10')
ON CONFLICT (key) DO NOTHING;

SELECT pg_notify('pgrst', 'reload schema');

-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/015_platform_hardening.sql
-- ═══════════════════════════════════════════════════════════════

-- AuroWater production hardening:
-- contact subjects, inventory reservation, payout requests, and atomic supplier transitions.
-- Idempotent.

ALTER TABLE public.contact_submissions
  ADD COLUMN IF NOT EXISTS subject TEXT;

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS accepted_at TIMESTAMPTZ;

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS stock_reserved_qty INTEGER NOT NULL DEFAULT 0
    CHECK (stock_reserved_qty >= 0);

ALTER TABLE public.supplier_stock
  ADD COLUMN IF NOT EXISTS reserved_cans INTEGER NOT NULL DEFAULT 0
    CHECK (reserved_cans >= 0);

-- Payout requests are separate from completed payout records so a request can be
-- audited through pending -> processing -> paid/rejected without pretending money moved.
CREATE TABLE IF NOT EXISTS public.payout_requests (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  supplier_id         UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  amount              NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  method              TEXT NOT NULL DEFAULT 'upi'
                        CHECK (method IN ('upi','bank')),
  destination_reference TEXT,
  status              TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','processing','paid','rejected','cancelled')),
  notes               TEXT,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at        TIMESTAMPTZ,
  processed_by        UUID REFERENCES public.profiles(id)
);

CREATE INDEX IF NOT EXISTS payout_requests_supplier_created_idx
  ON public.payout_requests(supplier_id, created_at DESC);

CREATE INDEX IF NOT EXISTS payout_requests_status_created_idx
  ON public.payout_requests(status, created_at ASC);

ALTER TABLE public.payout_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "payout_requests_select_own_or_admin" ON public.payout_requests;
CREATE POLICY "payout_requests_select_own_or_admin" ON public.payout_requests
  FOR SELECT USING (
    supplier_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "payout_requests_insert_own_or_admin" ON public.payout_requests;
CREATE POLICY "payout_requests_insert_own_or_admin" ON public.payout_requests
  FOR INSERT WITH CHECK (
    supplier_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "payout_requests_update_admin" ON public.payout_requests;
CREATE POLICY "payout_requests_update_admin" ON public.payout_requests
  FOR UPDATE USING (COALESCE(public.current_profile_role(), '') = 'admin')
  WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

DROP TRIGGER IF EXISTS payout_requests_updated_at ON public.payout_requests;
CREATE TRIGGER payout_requests_updated_at
  BEFORE UPDATE ON public.payout_requests
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

GRANT EXECUTE ON FUNCTION public.reserve_supplier_stock(UUID, INTEGER) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.release_supplier_stock(UUID, INTEGER) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.consume_supplier_reserved_stock(UUID, INTEGER) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.supplier_accept_order(UUID, UUID) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.supplier_complete_order(UUID, UUID) TO authenticated, service_role;

-- Atomic stock reserve: available stock is reduced immediately and moved into reserved stock.
CREATE OR REPLACE FUNCTION public.reserve_supplier_stock(
  p_supplier_id UUID,
  p_quantity INTEGER
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_quantity IS NULL OR p_quantity <= 0 THEN
    RETURN FALSE;
  END IF;

  UPDATE public.supplier_stock
  SET
    cans_available = cans_available - p_quantity,
    reserved_cans = reserved_cans + p_quantity,
    updated_at = NOW()
  WHERE supplier_id = p_supplier_id
    AND cans_available >= p_quantity;

  RETURN FOUND;
END;
$$;

-- Release an accepted reservation back into available stock.
CREATE OR REPLACE FUNCTION public.release_supplier_stock(
  p_supplier_id UUID,
  p_quantity INTEGER
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_quantity IS NULL OR p_quantity <= 0 THEN
    RETURN FALSE;
  END IF;

  UPDATE public.supplier_stock
  SET
    cans_available = cans_available + p_quantity,
    reserved_cans = GREATEST(0, reserved_cans - p_quantity),
    updated_at = NOW()
  WHERE supplier_id = p_supplier_id
    AND reserved_cans >= p_quantity;

  RETURN FOUND;
END;
$$;

-- Disable the legacy completion trigger. New order completion consumes reserved stock atomically.
DROP TRIGGER IF EXISTS trg_deduct_stock ON public.orders;

-- Consume reserved stock after successful delivery.
CREATE OR REPLACE FUNCTION public.consume_supplier_reserved_stock(
  p_supplier_id UUID,
  p_quantity INTEGER
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_quantity IS NULL OR p_quantity <= 0 THEN
    RETURN TRUE;
  END IF;

  UPDATE public.supplier_stock
  SET
    reserved_cans = reserved_cans - p_quantity,
    updated_at = NOW()
  WHERE supplier_id = p_supplier_id
    AND reserved_cans >= p_quantity;

  RETURN FOUND;
END;
$$;

-- One transaction for supplier acceptance + reservation.
-- This is the authoritative "accept" operation.
CREATE OR REPLACE FUNCTION public.supplier_accept_order(
  p_order_id UUID,
  p_supplier_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.orders%ROWTYPE;
  v_qty INTEGER;
  v_reserved INTEGER;
  v_is_can_order BOOLEAN;
  v_service_key TEXT;
  v_now TIMESTAMPTZ := NOW();
BEGIN
  SELECT *
  INTO v_order
  FROM public.orders
  WHERE id = p_order_id
    AND supplier_id = p_supplier_id
    AND status = 'ASSIGNED'
    AND accepted_at IS NULL
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'ok', false,
      'reason', 'not_assignable'
    );
  END IF;

  v_qty := GREATEST(1, COALESCE(v_order.can_quantity, 1));

  SELECT lower(key)
  INTO v_service_key
  FROM public.service_types
  WHERE id = v_order.service_type_id;

  v_is_can_order := COALESCE(v_service_key, '') = 'water_can';

  IF NOT v_is_can_order THEN
    UPDATE public.orders
    SET
      accepted_at = v_now,
      stock_reserved_qty = 0,
      updated_at = v_now
    WHERE id = p_order_id;

    UPDATE public.order_dispatch
    SET
      status = 'ACCEPTED',
      responded_at = v_now
    WHERE order_id = p_order_id
      AND supplier_id = p_supplier_id
      AND status = 'ASSIGNED';

    RETURN jsonb_build_object(
      'ok', true,
      'customer_id', v_order.customer_id,
      'reserved_qty', 0
    );
  END IF;

  INSERT INTO public.supplier_stock (supplier_id, cans_available, reserved_cans, low_stock_alert)
  VALUES (p_supplier_id, 0, 0, 10)
  ON CONFLICT (supplier_id) DO NOTHING;

  SELECT reserved_cans
  INTO v_reserved
  FROM public.supplier_stock
  WHERE supplier_id = p_supplier_id
  FOR UPDATE;

  IF NOT EXISTS (
    SELECT 1
    FROM public.supplier_stock
    WHERE supplier_id = p_supplier_id
      AND cans_available >= v_qty
  ) THEN
    RETURN jsonb_build_object(
      'ok', false,
      'reason', 'insufficient_stock',
      'required', v_qty
    );
  END IF;

  UPDATE public.supplier_stock
  SET
    cans_available = cans_available - v_qty,
    reserved_cans = reserved_cans + v_qty,
    updated_at = v_now
  WHERE supplier_id = p_supplier_id;

  UPDATE public.orders
  SET
    accepted_at = v_now,
    stock_reserved_qty = v_qty,
    updated_at = v_now
  WHERE id = p_order_id;

  UPDATE public.order_dispatch
  SET
    status = 'ACCEPTED',
    responded_at = v_now
  WHERE order_id = p_order_id
    AND supplier_id = p_supplier_id
    AND status = 'ASSIGNED';

  RETURN jsonb_build_object(
    'ok', true,
    'customer_id', v_order.customer_id,
    'reserved_qty', v_qty
  );
END;
$$;

-- One transaction for supplier completion + reserved-stock consumption.
CREATE OR REPLACE FUNCTION public.supplier_complete_order(
  p_order_id UUID,
  p_supplier_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_order public.orders%ROWTYPE;
  v_qty INTEGER;
  v_now TIMESTAMPTZ := NOW();
BEGIN
  SELECT *
  INTO v_order
  FROM public.orders
  WHERE id = p_order_id
    AND supplier_id = p_supplier_id
    AND status = 'IN_PROGRESS'
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'reason', 'invalid_transition');
  END IF;

  v_qty := GREATEST(0, COALESCE(v_order.stock_reserved_qty, 0));

  IF v_qty > 0 THEN
    UPDATE public.supplier_stock
    SET
      reserved_cans = reserved_cans - v_qty,
      updated_at = v_now
    WHERE supplier_id = p_supplier_id
      AND reserved_cans >= v_qty;

    IF NOT FOUND THEN
      RETURN jsonb_build_object('ok', false, 'reason', 'reserved_stock_missing');
    END IF;
  END IF;

  UPDATE public.orders
  SET
    status = 'COMPLETED',
    completed_at = COALESCE(completed_at, v_now),
    stock_reserved_qty = 0,
    payout_status = COALESCE(payout_status, 'pending'),
    updated_at = v_now
  WHERE id = p_order_id;

  UPDATE public.profiles
  SET completed_orders = COALESCE(completed_orders, 0) + 1,
      updated_at = v_now
  WHERE id = p_supplier_id;

  RETURN jsonb_build_object(
    'ok', true,
    'customer_id', v_order.customer_id,
    'reserved_qty', v_qty
  );
END;
$$;

SELECT pg_notify('pgrst', 'reload schema');

-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/016_supplier_operations_foundation.sql
-- ═══════════════════════════════════════════════════════════════

-- 016_supplier_operations_foundation.sql
-- AuroWater production schema alignment:
-- service zones, supplier-zone mapping, dispatch attempt ledger,
-- address/order compatibility fields, payment compatibility,
-- immutable supplier payout snapshots, and atomic payout-request creation.
-- Idempotent: safe to run repeatedly.

CREATE TABLE IF NOT EXISTS public.service_zones (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  city          TEXT NOT NULL,
  name          TEXT NOT NULL,
  slug          TEXT NOT NULL UNIQUE,
  status        TEXT NOT NULL DEFAULT 'COMING_SOON'
                  CHECK (status IN ('AVAILABLE','LIMITED','TEMPORARILY_UNAVAILABLE','COMING_SOON')),
  pincodes      TEXT[] NOT NULL DEFAULT '{}',
  center_lat    NUMERIC(9,6),
  center_lng    NUMERIC(9,6),
  radius_km     NUMERIC(8,2),
  services      TEXT[],
  is_catch_all  BOOLEAN NOT NULL DEFAULT false,
  notes         TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS service_zones_city_status_idx
  ON public.service_zones(city, status);
CREATE INDEX IF NOT EXISTS service_zones_pincode_gin_idx
  ON public.service_zones USING GIN(pincodes);

ALTER TABLE public.service_zones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_zones_select_admin" ON public.service_zones;
CREATE POLICY "service_zones_select_admin" ON public.service_zones
  FOR SELECT USING (COALESCE(public.current_profile_role(), '') = 'admin');

DROP POLICY IF EXISTS "service_zones_write_admin" ON public.service_zones;
CREATE POLICY "service_zones_write_admin" ON public.service_zones
  FOR ALL USING (COALESCE(public.current_profile_role(), '') = 'admin')
  WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

DROP TRIGGER IF EXISTS service_zones_updated_at ON public.service_zones;
CREATE TRIGGER service_zones_updated_at
  BEFORE UPDATE ON public.service_zones
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE TABLE IF NOT EXISTS public.supplier_zones (
  supplier_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  zone_id     UUID NOT NULL REFERENCES public.service_zones(id) ON DELETE CASCADE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (supplier_id, zone_id)
);

CREATE INDEX IF NOT EXISTS supplier_zones_zone_supplier_idx
  ON public.supplier_zones(zone_id, supplier_id);

ALTER TABLE public.supplier_zones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "supplier_zones_select_own_or_admin" ON public.supplier_zones;
CREATE POLICY "supplier_zones_select_own_or_admin" ON public.supplier_zones
  FOR SELECT USING (
    supplier_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "supplier_zones_admin_write" ON public.supplier_zones;
CREATE POLICY "supplier_zones_admin_write" ON public.supplier_zones
  FOR ALL USING (COALESCE(public.current_profile_role(), '') = 'admin')
  WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

CREATE TABLE IF NOT EXISTS public.order_dispatch (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id      UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  supplier_id   UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status        TEXT NOT NULL DEFAULT 'ASSIGNED'
                  CHECK (status IN ('ASSIGNED','ACCEPTED','REJECTED','EXPIRED','CANCELLED')),
  attempt_no    INTEGER NOT NULL DEFAULT 1 CHECK (attempt_no > 0),
  distance_km   NUMERIC(8,2),
  reason        TEXT,
  assigned_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  responded_at  TIMESTAMPTZ,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(order_id, supplier_id)
);

CREATE INDEX IF NOT EXISTS order_dispatch_order_status_idx
  ON public.order_dispatch(order_id, status);
CREATE INDEX IF NOT EXISTS order_dispatch_supplier_status_idx
  ON public.order_dispatch(supplier_id, status);

ALTER TABLE public.order_dispatch ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "order_dispatch_select_own_or_admin" ON public.order_dispatch;
CREATE POLICY "order_dispatch_select_own_or_admin" ON public.order_dispatch
  FOR SELECT USING (
    supplier_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "order_dispatch_admin_write" ON public.order_dispatch;
CREATE POLICY "order_dispatch_admin_write" ON public.order_dispatch
  FOR ALL USING (COALESCE(public.current_profile_role(), '') = 'admin')
  WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

DROP TRIGGER IF EXISTS order_dispatch_updated_at ON public.order_dispatch;
CREATE TRIGGER order_dispatch_updated_at
  BEFORE UPDATE ON public.order_dispatch
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- Supplier can create its own settings row on first login; admin retains full access.
DROP POLICY IF EXISTS "supplier_settings_insert_admin" ON public.supplier_settings;
DROP POLICY IF EXISTS "supplier_settings_insert_own_or_admin" ON public.supplier_settings;
CREATE POLICY "supplier_settings_insert_own_or_admin" ON public.supplier_settings
  FOR INSERT WITH CHECK (
    user_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

ALTER TABLE public.addresses
  ADD COLUMN IF NOT EXISTS customer_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS line1 TEXT,
  ADD COLUMN IF NOT EXISTS line2 TEXT,
  ADD COLUMN IF NOT EXISTS state TEXT,
  ADD COLUMN IF NOT EXISTS lat NUMERIC(9,6),
  ADD COLUMN IF NOT EXISTS lng NUMERIC(9,6),
  ADD COLUMN IF NOT EXISTS zone_id UUID REFERENCES public.service_zones(id);

UPDATE public.addresses
SET
  customer_id = COALESCE(customer_id, user_id),
  line1 = COALESCE(line1, house_flat),
  line2 = COALESCE(line2, area),
  state = COALESCE(NULLIF(TRIM(state), ''), 'Uttar Pradesh')
WHERE customer_id IS NULL
   OR line1 IS NULL
   OR line2 IS NULL
   OR state IS NULL
   OR TRIM(state) = '';

CREATE INDEX IF NOT EXISTS addresses_customer_created_idx
  ON public.addresses(customer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS addresses_zone_idx
  ON public.addresses(zone_id);

CREATE OR REPLACE FUNCTION public.sync_address_contract()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  IF NEW.customer_id IS NULL THEN
    NEW.customer_id := NEW.user_id;
  END IF;
  IF NEW.user_id IS NULL THEN
    NEW.user_id := NEW.customer_id;
  END IF;
  IF NEW.line1 IS NULL OR TRIM(NEW.line1) = '' THEN
    NEW.line1 := NEW.house_flat;
  END IF;
  IF NEW.line2 IS NULL OR TRIM(NEW.line2) = '' THEN
    NEW.line2 := NEW.area;
  END IF;
  IF NEW.house_flat IS NULL OR TRIM(NEW.house_flat) = '' THEN
    NEW.house_flat := NEW.line1;
  END IF;
  IF NEW.area IS NULL OR TRIM(NEW.area) = '' THEN
    NEW.area := NEW.line2;
  END IF;
  IF NEW.state IS NULL OR TRIM(NEW.state) = '' THEN
    NEW.state := 'Uttar Pradesh';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS addresses_sync_contract ON public.addresses;
CREATE TRIGGER addresses_sync_contract
  BEFORE INSERT OR UPDATE ON public.addresses
  FOR EACH ROW EXECUTE FUNCTION public.sync_address_contract();

DROP POLICY IF EXISTS "addresses_insert_customer_or_admin" ON public.addresses;
CREATE POLICY "addresses_insert_customer_or_admin" ON public.addresses
  FOR INSERT WITH CHECK (
    customer_id = auth.uid()
    OR user_id = auth.uid()
    OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS service_type TEXT,
  ADD COLUMN IF NOT EXISTS final_amount NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS note TEXT,
  ADD COLUMN IF NOT EXISTS subscription_id UUID,
  ADD COLUMN IF NOT EXISTS can_count INTEGER,
  ADD COLUMN IF NOT EXISTS assigned_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dispatched_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS dispatch_attempts INTEGER NOT NULL DEFAULT 0 CHECK (dispatch_attempts >= 0),
  ADD COLUMN IF NOT EXISTS last_dispatch_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS supplier_note TEXT,
  ADD COLUMN IF NOT EXISTS tracking_url TEXT,
  ADD COLUMN IF NOT EXISTS rating INTEGER CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
  ADD COLUMN IF NOT EXISTS review_text TEXT,
  ADD COLUMN IF NOT EXISTS otp TEXT,
  ADD COLUMN IF NOT EXISTS otp_verified BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS source TEXT,
  ADD COLUMN IF NOT EXISTS promo_code TEXT,
  ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS has_review BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS supplier_payout_rate_snapshot NUMERIC(6,2) NOT NULL DEFAULT 0;

UPDATE public.orders o
SET
  service_type = COALESCE(o.service_type, st.key),
  final_amount = COALESCE(o.final_amount, o.total_amount),
  can_count = COALESCE(o.can_count, o.can_quantity),
  note = COALESCE(o.note, o.notes)
FROM public.service_types st
WHERE st.id = o.service_type_id
  AND (
    o.service_type IS NULL
    OR o.final_amount IS NULL
    OR o.can_count IS NULL
    OR o.note IS NULL
  );

ALTER TABLE public.orders
  DROP CONSTRAINT IF EXISTS orders_payment_status_check;

ALTER TABLE public.orders
  ADD CONSTRAINT orders_payment_status_check_v2
  CHECK (payment_status IN ('pending','unpaid','paid','refunded','failed'));

CREATE OR REPLACE FUNCTION public.sync_order_contract()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  resolved_service_id INTEGER;
  resolved_service_key TEXT;
BEGIN
  IF TG_OP = 'INSERT' OR NEW.service_type IS DISTINCT FROM OLD.service_type THEN
    IF NEW.service_type IS NOT NULL AND TRIM(NEW.service_type) <> '' THEN
      SELECT id, key
      INTO resolved_service_id, resolved_service_key
      FROM public.service_types
      WHERE key = NEW.service_type
        AND is_active = true
      LIMIT 1;
      IF resolved_service_id IS NOT NULL THEN
        NEW.service_type_id := resolved_service_id;
        NEW.service_type := resolved_service_key;
      END IF;
    END IF;
  END IF;

  IF NEW.service_type IS NULL AND NEW.service_type_id IS NOT NULL THEN
    SELECT key INTO NEW.service_type
    FROM public.service_types
    WHERE id = NEW.service_type_id
    LIMIT 1;
  END IF;

  IF NEW.can_count IS NULL AND NEW.can_quantity IS NOT NULL THEN
    NEW.can_count := NEW.can_quantity;
  END IF;

  IF NEW.can_quantity IS NULL AND NEW.can_count IS NOT NULL THEN
    NEW.can_quantity := NEW.can_count;
  END IF;

  IF NEW.final_amount IS NULL THEN
    NEW.final_amount := NEW.total_amount;
  END IF;

  IF NEW.note IS NULL THEN
    NEW.note := NEW.notes;
  END IF;

  IF NEW.notes IS NULL THEN
    NEW.notes := NEW.note;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS orders_sync_contract ON public.orders;
CREATE TRIGGER orders_sync_contract
  BEFORE INSERT OR UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.sync_order_contract();

CREATE OR REPLACE FUNCTION public.snapshot_supplier_payout()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
DECLARE
  configured_pct NUMERIC(6,2);
BEGIN
  IF TG_OP = 'INSERT' THEN
    SELECT NULLIF(regexp_replace(value, '[^0-9.\-]', '', 'g'), '')::NUMERIC
    INTO configured_pct
    FROM public.settings
    WHERE key = 'supplier_commission'
    LIMIT 1;

    configured_pct := GREATEST(0, LEAST(100, COALESCE(configured_pct, 30)));
    NEW.supplier_payout_rate_snapshot := configured_pct;

    IF COALESCE(NEW.supplier_payout, 0) = 0
       AND COALESCE(NEW.total_amount, 0) > 0 THEN
      NEW.supplier_payout :=
        ROUND((NEW.total_amount * configured_pct / 100.0)::NUMERIC, 2);
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS orders_supplier_payout_snapshot ON public.orders;
CREATE TRIGGER orders_supplier_payout_snapshot
  BEFORE INSERT ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.snapshot_supplier_payout();

DO $$
DECLARE
  pct NUMERIC(6,2);
BEGIN
  SELECT GREATEST(0, LEAST(100, COALESCE(
    NULLIF(regexp_replace(value, '[^0-9.\-]', '', 'g'), '')::NUMERIC,
    30
  ))) INTO pct
  FROM public.settings
  WHERE key = 'supplier_commission'
  LIMIT 1;

  pct := COALESCE(pct, 30);

  UPDATE public.orders
  SET supplier_payout_rate_snapshot = pct,
      supplier_payout = ROUND((total_amount * pct / 100.0)::NUMERIC, 2)
  WHERE status IN ('PENDING','ASSIGNED','IN_PROGRESS')
    AND COALESCE(supplier_payout, 0) = 0
    AND total_amount > 0;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_supplier_payout_request(
  p_supplier_id UUID,
  p_amount NUMERIC,
  p_method TEXT,
  p_destination_reference TEXT,
  p_notes TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  locked_id UUID;
  eligible NUMERIC(12,2);
  already_requested NUMERIC(12,2);
  available NUMERIC(12,2);
  inserted_request public.payout_requests%ROWTYPE;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'INVALID_AMOUNT';
  END IF;
  IF p_method NOT IN ('upi','bank') THEN
    RAISE EXCEPTION 'INVALID_METHOD';
  END IF;

  SELECT id INTO locked_id
  FROM public.profiles
  WHERE id = p_supplier_id
    AND role = 'supplier'
  FOR UPDATE;

  IF locked_id IS NULL THEN
    RAISE EXCEPTION 'SUPPLIER_NOT_FOUND';
  END IF;

  SELECT COALESCE(SUM(supplier_payout), 0)
  INTO eligible
  FROM public.orders
  WHERE supplier_id = p_supplier_id
    AND status = 'COMPLETED'
    AND payout_status = 'pending';

  SELECT COALESCE(SUM(amount), 0)
  INTO already_requested
  FROM public.payout_requests
  WHERE supplier_id = p_supplier_id
    AND status IN ('pending','processing');

  available := GREATEST(0, ROUND((eligible - already_requested)::NUMERIC, 2));

  IF p_amount > available THEN
    RAISE EXCEPTION 'PAYOUT_BALANCE_EXCEEDED:%', available;
  END IF;

  INSERT INTO public.payout_requests (
    supplier_id, amount, method, destination_reference, status, notes
  )
  VALUES (
    p_supplier_id,
    ROUND(p_amount::NUMERIC, 2),
    p_method,
    NULLIF(TRIM(p_destination_reference), ''),
    'pending',
    NULLIF(TRIM(p_notes), '')
  )
  RETURNING * INTO inserted_request;

  RETURN jsonb_build_object(
    'id', inserted_request.id,
    'supplier_id', inserted_request.supplier_id,
    'amount', inserted_request.amount,
    'method', inserted_request.method,
    'status', inserted_request.status,
    'destination_reference', inserted_request.destination_reference,
    'notes', inserted_request.notes,
    'created_at', inserted_request.created_at
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_supplier_payout_request(UUID, NUMERIC, TEXT, TEXT, TEXT)
  TO service_role;

SELECT pg_notify('pgrst', 'reload schema');
