-- AUTO-GENERATED by scripts/build-supabase-migrations.mjs — do not edit by hand.
-- Run in Supabase SQL Editor (Project → SQL) in order is already preserved.


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/001_core_schema.sql
-- ═══════════════════════════════════════════════════════════════

-- AuroWater — core schema (Supabase / PostgreSQL)
-- Idempotent: safe to run multiple times.
-- Requires: auth.users (Supabase Auth)

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ── Users (extends Supabase auth.users) ─────────────────────────────
CREATE TABLE IF NOT EXISTS public.profiles (
  id              UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name       TEXT NOT NULL DEFAULT '',
  email           TEXT NOT NULL UNIQUE,
  phone           TEXT,
  role            TEXT NOT NULL DEFAULT 'customer'
                    CHECK (role IN ('customer','technician','supplier','admin')),
  aurotap_id      TEXT UNIQUE,
  avatar_url      TEXT,
  is_active       BOOLEAN NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Service types ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.service_types (
  id          SERIAL PRIMARY KEY,
  key         TEXT NOT NULL UNIQUE,
  name        TEXT NOT NULL,
  description TEXT,
  base_price  NUMERIC(10,2) NOT NULL DEFAULT 0,
  unit        TEXT NOT NULL DEFAULT 'per visit',
  is_active   BOOLEAN NOT NULL DEFAULT true,
  sort_order  INTEGER NOT NULL DEFAULT 0
);

-- ── Addresses ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.addresses (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  label       TEXT DEFAULT 'Home',
  house_flat  TEXT NOT NULL,
  area        TEXT NOT NULL,
  city        TEXT NOT NULL,
  pincode     TEXT NOT NULL,
  landmark    TEXT,
  is_default  BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Orders ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.orders (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_number        TEXT UNIQUE NOT NULL,
  customer_id         UUID NOT NULL REFERENCES public.profiles(id),
  supplier_id         UUID REFERENCES public.profiles(id),
  technician_id       UUID REFERENCES public.profiles(id),
  service_type_id     INTEGER NOT NULL REFERENCES public.service_types(id),
  sub_option_key      TEXT,
  address_id          UUID REFERENCES public.addresses(id),
  address_snapshot    JSONB,
  scheduled_date      DATE,
  time_slot           TEXT,
  scheduled_time      TIMESTAMPTZ,
  status              TEXT NOT NULL DEFAULT 'PENDING'
                        CHECK (status IN ('PENDING','ASSIGNED','IN_PROGRESS','COMPLETED','CANCELLED')),
  base_amount         NUMERIC(10,2) NOT NULL DEFAULT 0,
  convenience_fee     NUMERIC(10,2) NOT NULL DEFAULT 29,
  emergency_charge    NUMERIC(10,2) NOT NULL DEFAULT 0,
  gst_amount          NUMERIC(10,2) NOT NULL DEFAULT 0,
  total_amount        NUMERIC(10,2) NOT NULL DEFAULT 0,
  supplier_payout     NUMERIC(10,2) NOT NULL DEFAULT 0,
  platform_fee        NUMERIC(10,2) NOT NULL DEFAULT 0,
  payment_method      TEXT DEFAULT 'cash' CHECK (payment_method IN ('cash','online','upi','card')),
  payment_status      TEXT NOT NULL DEFAULT 'unpaid'
                        CHECK (payment_status IN ('unpaid','paid','refunded')),
  payout_status       TEXT NOT NULL DEFAULT 'pending'
                        CHECK (payout_status IN ('pending','processing','paid')),
  is_emergency        BOOLEAN NOT NULL DEFAULT false,
  cancellation_reason TEXT,
  notes               TEXT,
  can_quantity        INTEGER,
  can_price_per_unit  NUMERIC(10,2),
  can_order_type      TEXT CHECK (can_order_type IS NULL OR can_order_type IN ('one_time','subscription')),
  can_frequency       TEXT CHECK (can_frequency IS NULL OR can_frequency IN ('daily','alternate','weekly')),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Settings (key-value) ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.settings (
  key         TEXT PRIMARY KEY,
  value       TEXT NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Payouts ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.payouts (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  supplier_id UUID NOT NULL REFERENCES public.profiles(id),
  amount      NUMERIC(10,2) NOT NULL,
  method      TEXT,
  reference   TEXT,
  paid_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  notes       TEXT
);

-- ── Reviews ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.reviews (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id    UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  customer_id UUID NOT NULL REFERENCES public.profiles(id),
  rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment     TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT reviews_order_unique UNIQUE (order_id)
);

-- ── Notifications ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.notifications (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title       TEXT NOT NULL,
  body        TEXT NOT NULL,
  type        TEXT NOT NULL DEFAULT 'system',
  order_id    UUID REFERENCES public.orders(id),
  is_read     BOOLEAN NOT NULL DEFAULT false,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Contact submissions (marketing / support) ───────────────────────
CREATE TABLE IF NOT EXISTS public.contact_submissions (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT NOT NULL,
  email       TEXT NOT NULL,
  phone       TEXT,
  message     TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Founding members counter (social proof) ──────────────────────────
CREATE TABLE IF NOT EXISTS public.founding_members (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name        TEXT,
  email       TEXT,
  phone       TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS founding_members_phone_key ON public.founding_members (phone)
  WHERE phone IS NOT NULL AND phone <> '';


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/002_rls_policies.sql
-- ═══════════════════════════════════════════════════════════════

-- RLS policies for AuroWater (Supabase)
-- Idempotent: DROP POLICY IF EXISTS + CREATE POLICY

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.founding_members ENABLE ROW LEVEL SECURITY;

-- ── Helper: current profile role (avoids recursion in simple cases) ──
CREATE OR REPLACE FUNCTION public.current_profile_role()
RETURNS TEXT
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid() LIMIT 1;
$$;

-- ── profiles ───────────────────────────────────────────────────────
DROP POLICY IF EXISTS "profiles_select_own_or_admin" ON public.profiles;
CREATE POLICY "profiles_select_own_or_admin" ON public.profiles
  FOR SELECT USING (
    auth.uid() = id OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "profiles_update_own_or_admin" ON public.profiles;
CREATE POLICY "profiles_update_own_or_admin" ON public.profiles
  FOR UPDATE USING (
    auth.uid() = id OR COALESCE(public.current_profile_role(), '') = 'admin'
  )
  WITH CHECK (
    auth.uid() = id OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

-- Inserts handled by trigger / service role on signup
DROP POLICY IF EXISTS "profiles_insert_admin" ON public.profiles;
CREATE POLICY "profiles_insert_admin" ON public.profiles
  FOR INSERT WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── service_types (public read active; admin write) ─────────────────
DROP POLICY IF EXISTS "service_types_select_all" ON public.service_types;
CREATE POLICY "service_types_select_all" ON public.service_types
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "service_types_write_admin" ON public.service_types;
CREATE POLICY "service_types_write_admin" ON public.service_types
  FOR ALL USING (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── addresses ───────────────────────────────────────────────────────
DROP POLICY IF EXISTS "addresses_crud_own" ON public.addresses;
CREATE POLICY "addresses_crud_own" ON public.addresses
  FOR ALL USING (
    user_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  )
  WITH CHECK (
    user_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

-- ── orders ──────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "orders_select_policy" ON public.orders;
CREATE POLICY "orders_select_policy" ON public.orders
  FOR SELECT USING (
    customer_id = auth.uid()
    OR supplier_id = auth.uid()
    OR technician_id = auth.uid()
    OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "orders_insert_customer" ON public.orders;
CREATE POLICY "orders_insert_customer" ON public.orders
  FOR INSERT WITH CHECK (customer_id = auth.uid());

DROP POLICY IF EXISTS "orders_update_roles" ON public.orders;
CREATE POLICY "orders_update_roles" ON public.orders
  FOR UPDATE USING (
    customer_id = auth.uid()
    OR supplier_id = auth.uid()
    OR technician_id = auth.uid()
    OR COALESCE(public.current_profile_role(), '') = 'admin'
  )
  WITH CHECK (
    customer_id = auth.uid()
    OR supplier_id = auth.uid()
    OR technician_id = auth.uid()
    OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "orders_delete_admin" ON public.orders;
CREATE POLICY "orders_delete_admin" ON public.orders
  FOR DELETE USING (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── settings ───────────────────────────────────────────────────────
DROP POLICY IF EXISTS "settings_select_all" ON public.settings;
CREATE POLICY "settings_select_all" ON public.settings
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "settings_write_admin" ON public.settings;
CREATE POLICY "settings_write_admin" ON public.settings
  FOR INSERT WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

DROP POLICY IF EXISTS "settings_update_admin" ON public.settings;
CREATE POLICY "settings_update_admin" ON public.settings
  FOR UPDATE USING (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── payouts ─────────────────────────────────────────────────────────
DROP POLICY IF EXISTS "payouts_select" ON public.payouts;
CREATE POLICY "payouts_select" ON public.payouts
  FOR SELECT USING (
    supplier_id = auth.uid()
    OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "payouts_write_admin" ON public.payouts;
CREATE POLICY "payouts_write_admin" ON public.payouts
  FOR INSERT WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── reviews ───────────────────────────────────────────────────────
DROP POLICY IF EXISTS "reviews_select_all" ON public.reviews;
CREATE POLICY "reviews_select_all" ON public.reviews
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "reviews_insert_customer" ON public.reviews;
CREATE POLICY "reviews_insert_customer" ON public.reviews
  FOR INSERT WITH CHECK (customer_id = auth.uid());

-- ── notifications ───────────────────────────────────────────────────
DROP POLICY IF EXISTS "notifications_select_own" ON public.notifications;
CREATE POLICY "notifications_select_own" ON public.notifications
  FOR SELECT USING (
    user_id = auth.uid()
    OR COALESCE(public.current_profile_role(), '') = 'admin'
  );

DROP POLICY IF EXISTS "notifications_update_own" ON public.notifications;
CREATE POLICY "notifications_update_own" ON public.notifications
  FOR UPDATE USING (user_id = auth.uid() OR COALESCE(public.current_profile_role(), '') = 'admin');

DROP POLICY IF EXISTS "notifications_insert_admin" ON public.notifications;
CREATE POLICY "notifications_insert_admin" ON public.notifications
  FOR INSERT WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- ── contact_submissions (public insert for contact form; admin read) ─
DROP POLICY IF EXISTS "contact_select_admin" ON public.contact_submissions;
DROP POLICY IF EXISTS "contact_insert_any" ON public.contact_submissions;
CREATE POLICY "contact_select_admin" ON public.contact_submissions
  FOR SELECT USING (COALESCE(public.current_profile_role(), '') = 'admin');
CREATE POLICY "contact_insert_any" ON public.contact_submissions
  FOR INSERT WITH CHECK (true);

-- ── founding_members ────────────────────────────────────────────────
DROP POLICY IF EXISTS "founding_select_all" ON public.founding_members;
CREATE POLICY "founding_select_all" ON public.founding_members
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "founding_insert_own" ON public.founding_members;
CREATE POLICY "founding_insert_own" ON public.founding_members
  FOR INSERT WITH CHECK (true);


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/003_seed_settings.sql
-- ═══════════════════════════════════════════════════════════════

-- Default platform settings + service catalogue
-- Idempotent

INSERT INTO public.service_types (key, name, description, base_price, unit, is_active, sort_order) VALUES
  ('water_can', 'Water Can (20L)', 'RO-purified BIS-certified 20L sealed water cans.', 12, 'per can', true, 1),
  ('water_tanker', 'Water Tanker', 'Bulk water delivery via tanker.', 299, 'per delivery', true, 2),
  ('ro_service', 'RO Service & Repair', 'RO purifier service, filter change, AMC.', 199, 'per visit', true, 3),
  ('plumbing', 'Plumbing', 'Pipe fitting, leakage repair, installation.', 149, 'per visit', true, 4),
  ('borewell', 'Borewell Services', 'Borewell drilling, repair, motor fitting.', 499, 'per service', true, 5),
  ('motor_pump', 'Motor & Pump Repair', 'Submersible motor repair, pump installation.', 249, 'per visit', true, 6),
  ('tank_cleaning', 'Water Tank Cleaning', 'Overhead/underground tank cleaning.', 349, 'per tank', true, 7)
ON CONFLICT (key) DO NOTHING;

INSERT INTO public.settings (key, value) VALUES
  ('default_can_price',        '12'),
  ('subscription_can_price',   '10'),
  ('bulk_can_price',           '9'),
  ('bulk_threshold',           '50'),
  ('market_can_price',         '20'),
  ('water_tanker_price',       '299'),
  ('ro_service_price',         '199'),
  ('plumbing_price',           '149'),
  ('borewell_price',           '499'),
  ('motor_pump_price',         '249'),
  ('tank_cleaning_price',      '349'),
  ('convenience_fee',          '29'),
  ('emergency_surcharge',      '199'),
  ('gst_rate',                 '18'),
  ('bulk_commission',          '8'),
  ('technician_commission',    '50'),
  ('supplier_commission',      '30'),
  ('support_email',            'support.aurotap@gmail.com'),
  ('secondary_email',          'aurotap@gmail.com'),
  ('phone_primary',            '9889305803'),
  ('phone_secondary',          ''),
  ('office_address',           'Kanpur, Uttar Pradesh'),
  ('working_hours',            '09:00–21:00 IST'),
  ('brand_name',               'Auro Water'),
  ('whatsapp_enabled',         '1'),
  ('service_base_prices',      '{"water_tanker":299,"ro_service":199,"plumbing":149,"borewell":499,"motor_pump":249,"tank_cleaning":349}')
ON CONFLICT (key) DO NOTHING;


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/004_functions.sql
-- ═══════════════════════════════════════════════════════════════

-- Functions, triggers, auth profile bootstrap

-- ── 1) Order number generator ───────────────────────────────────────
CREATE OR REPLACE FUNCTION public.generate_order_number()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  candidate TEXT;
  tries INT := 0;
BEGIN
  LOOP
    candidate := 'AW-' || lpad((floor(random() * 100000000))::text, 8, '0');
    tries := tries + 1;
    EXIT WHEN NOT EXISTS (SELECT 1 FROM public.orders o WHERE o.order_number = candidate);
    EXIT WHEN tries > 50;
  END LOOP;
  IF tries > 50 THEN
    candidate := 'AW-' || replace(gen_random_uuid()::text, '-', '');
    candidate := left(candidate, 11);
  END IF;
  RETURN candidate;
END;
$$;

-- ── 2) updated_at trigger ───────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS profiles_updated_at ON public.profiles;
CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

DROP TRIGGER IF EXISTS orders_updated_at ON public.orders;
CREATE TRIGGER orders_updated_at
  BEFORE UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

-- ── 3) New Supabase Auth user → profile row ─────────────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  r TEXT;
  phone_val TEXT;
BEGIN
  r := COALESCE(NEW.raw_user_meta_data->>'role', 'customer');
  IF r NOT IN ('customer','technician','supplier','admin') THEN
    r := 'customer';
  END IF;
  phone_val := NULLIF(TRIM(COALESCE(NEW.raw_user_meta_data->>'phone', '')), '');
  INSERT INTO public.profiles (id, full_name, email, phone, role)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(NEW.email, ''),
    phone_val,
    r
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(NULLIF(EXCLUDED.full_name, ''), public.profiles.full_name);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS aurowater_on_auth_user_created ON auth.users;
CREATE TRIGGER aurowater_on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── 4) Customer stats ───────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_customer_stats(p_customer_id UUID)
RETURNS TABLE (
  total_orders BIGINT,
  completed_orders BIGINT,
  total_spent NUMERIC,
  estimated_savings NUMERIC
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    COUNT(*)::BIGINT,
    COUNT(*) FILTER (WHERE o.status = 'COMPLETED')::BIGINT,
    COALESCE(SUM(o.total_amount) FILTER (WHERE o.status = 'COMPLETED' AND o.payment_status = 'paid'), 0)::NUMERIC,
    COALESCE(SUM(o.total_amount) FILTER (WHERE o.status = 'COMPLETED') * 0.35, 0)::NUMERIC
  FROM public.orders o
  WHERE o.customer_id = p_customer_id;
$$;

-- ── 5) Supplier earnings by period ────────────────────────────────────
CREATE OR REPLACE FUNCTION public.get_supplier_earnings(p_supplier_id UUID, p_period TEXT)
RETURNS TABLE (
  period_label TEXT,
  order_count BIGINT,
  gross_amount NUMERIC,
  pending_payout NUMERIC
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  start_ts TIMESTAMPTZ;
  pl TEXT;
BEGIN
  pl := lower(coalesce(p_period, 'month'));
  start_ts := CASE pl
    WHEN 'today' THEN date_trunc('day', NOW())
    WHEN 'week' THEN date_trunc('week', NOW())
    WHEN 'month' THEN date_trunc('month', NOW())
    ELSE date_trunc('month', NOW())
  END;

  RETURN QUERY
  SELECT
    pl::TEXT,
    COUNT(*)::BIGINT,
    COALESCE(SUM(o.total_amount) FILTER (WHERE o.status = 'COMPLETED'), 0)::NUMERIC,
    COALESCE(SUM(o.supplier_payout) FILTER (WHERE o.payout_status = 'pending'), 0)::NUMERIC
  FROM public.orders o
  WHERE o.supplier_id = p_supplier_id
    AND o.created_at >= start_ts;
END;
$$;

-- Default order numbers when not supplied by app
ALTER TABLE public.orders
  ALTER COLUMN order_number SET DEFAULT (public.generate_order_number());


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/005_notifications_dedup.sql
-- ═══════════════════════════════════════════════════════════════

-- 005_notifications_dedup.sql
ALTER TABLE public.notifications
  ADD COLUMN IF NOT EXISTS dedup_key text;

DROP INDEX IF EXISTS notifications_user_dedup_key_idx;

CREATE UNIQUE INDEX IF NOT EXISTS notifications_dedup_key_idx
  ON public.notifications (dedup_key)
  WHERE dedup_key IS NOT NULL;

-- Enable Realtime (run on Supabase Postgres; skip if tables are already in publication)
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/006_schema_compat.sql
-- ═══════════════════════════════════════════════════════════════

-- 006_schema_compat.sql — additive fixes for code↔schema alignment (idempotent, no data deletion)
-- Run after 001–005. Safe to re-run.

-- Reviews flow: customer API updates orders.has_review
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS has_review BOOLEAN NOT NULL DEFAULT false;

-- Admin dashboard KPI: online technicians count
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS is_online BOOLEAN NOT NULL DEFAULT false;

-- Optional KPI tables referenced by /api/admin/dashboard (minimal stubs)
CREATE TABLE IF NOT EXISTS public.applications (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  status     TEXT NOT NULL DEFAULT 'pending',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.fraud_flags (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  resolved   BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fraud_flags ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "applications_admin_all" ON public.applications;
CREATE POLICY "applications_admin_all" ON public.applications
  FOR ALL USING (COALESCE(public.current_profile_role(), '') = 'admin')
  WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

DROP POLICY IF EXISTS "fraud_flags_admin_all" ON public.fraud_flags;
CREATE POLICY "fraud_flags_admin_all" ON public.fraud_flags
  FOR ALL USING (COALESCE(public.current_profile_role(), '') = 'admin')
  WITH CHECK (COALESCE(public.current_profile_role(), '') = 'admin');

-- Refresh PostgREST schema cache so /rest/v1/rpc and table routes see DDL above immediately.
-- Fixes persistent PGRST205 ("could not find the table in the schema cache") after migrations.
NOTIFY pgrst, 'reload schema';


-- ═══════════════════════════════════════════════════════════════
-- FILE: sql/006_production_readiness.sql
-- ═══════════════════════════════════════════════════════════════

-- sql/006_production_readiness.sql
-- Run AFTER sql/006_schema_compat.sql (or paste after full bundle).
-- Idempotent: no DROP, no RLS replacement (002_rls_policies.sql stays authoritative).

-- ── Ensure profile display IDs for existing rows ─────────────────────────
UPDATE public.profiles
SET aurotap_id = 'AW-' || upper(left(replace(id::text, '-', ''), 8))
WHERE aurotap_id IS NULL OR trim(both from aurotap_id) = '';

-- ── Service catalogue: bump metadata if seeds changed (matches app keys) ─
INSERT INTO public.service_types (key, name, description, base_price, unit, is_active, sort_order)
VALUES
  ('water_can', 'Water Can (20L)', 'RO-purified 20L cans', 12, 'per can', true, 1),
  ('water_tanker', 'Water Tanker', 'Bulk water delivery', 299, 'per delivery', true, 2),
  ('ro_service', 'RO Service & Repair', 'RO purifier service and repair', 199, 'per visit', true, 3),
  ('plumbing', 'Plumbing', 'Pipe fitting and repair', 149, 'per visit', true, 4),
  ('borewell', 'Borewell Services', 'Drilling and repair', 499, 'per service', true, 5),
  ('motor_pump', 'Motor & Pump Repair', 'Pump installation/repair', 249, 'per visit', true, 6),
  ('tank_cleaning', 'Water Tank Cleaning', 'Tank cleaning', 349, 'per tank', true, 7)
ON CONFLICT (key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  base_price = EXCLUDED.base_price,
  unit = EXCLUDED.unit,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order;

-- ── Reload PostgREST schema cache ───────────────────────────────────────
SELECT pg_notify('pgrst', 'reload schema');

-- ── Verification (expect 8 rows when core migration applied) ─────────────
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
    'profiles', 'orders', 'addresses', 'service_types',
    'settings', 'notifications', 'reviews', 'payouts'
  )
ORDER BY table_name;

